# PHP
# Test and package your PHP project.
# Add steps that run tests, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php

trigger:
- master

schedules:
- cron: "0 21-22 * * 0"
  displayName: Weekly build
  branches:
    include:
    - master
  always: true

pool:
  vmImage: ubuntu-latest

variables:
  phpVersion: 7.2

steps:
- script: |
    sudo update-alternatives --set php /usr/bin/php$(phpVersion)
    sudo update-alternatives --set phar /usr/bin/phar$(phpVersion)
    sudo update-alternatives --set phpdbg /usr/bin/phpdbg$(phpVersion)
    sudo update-alternatives --set php-cgi /usr/bin/php-cgi$(phpVersion)
    sudo update-alternatives --set phar.phar /usr/bin/phar.phar$(phpVersion)
    php -version
  displayName: 'Use PHP version $(phpVersion)'

- script: composer install --no-interaction --prefer-dist
  displayName: 'composer install'
- task: CmdLine@2
  inputs:
    script: 'curl -sSL https://www.sourceclear.com/install | bash'
- task: CmdLine@2
  inputs:
    script: 'srcclr scan .'
  env:
    SRCCLR_API_TOKEN: $(SRCCLR_API_TOKEN)
- task: CmdLine@2
  inputs:
    script: 'zip -r stackify-log-monolog.zip src/Stackify/Log/Monolog/Handler.php src/Stackify/Log/Monolog/LogEntry.php composer.json'
- task: Veracode@3
  inputs:
    ConnectionDetailsSelection: 'Endpoint'
    AnalysisService: 'Veracode'
    veracodeAppProfile: 'Retrace PHP Monolog library'
    version: 'AZ-Devops-Build-$(build.buildNumber)'
    filepath: 'stackify-log-monolog.zip'
    maximumWaitTime: '360'